services:
  commandbus:
    image: pcp1976/ocellicode-gpyt-commandbus:0.0.7
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - fluentd
      - db
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
    restart: always

  eventbus:
    image: pcp1976/ocellicode-gpyt-eventbus:0.0.2
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - fluentd
      - db
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
    restart: always

  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"

  # redis:
  #   image: redis
  #   volumes:
  #     - redis-data:/data
  #   depends_on:
  #     - fluentd
  #   ports:
  #     - "6379:6379"
  #   logging:
  #     driver: fluentd
  #     options:
  #       fluentd-address: localhost:24224
  #       fluentd-async-connect: "true"
  #   restart: always

  adminer:
    image: adminer
    ports:
      - 8181:8080
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
    restart: always

  fluentd:
    image: local-fd:latest
    build:
      context: ./fluent
    volumes:
      - ./fluent/fluent.conf:/fluentd/etc/fluent.conf
    environment:
      - FLUENTD_CONF=fluent.conf
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    restart: always

volumes:
  postgres-data:
  esdata:
  # redis-data:
